(function(root){'use strict';
const M=root.Mayor||(typeof require==='function'?require('./mayor.js'):null);
const choices={school:[['normal','Обычно',0],['shifts','Две смены',2],['remote','Дистанционно',2]],work:[['normal','Обычно',0],['limited','Чередование групп',1],['remote','Удалённо',2]],shops:[['both','Оба магазина',0],['mall','Только ТЦ',0],['market','Только магазин',0]],bus:[['frequent','Частые рейсы',2],['normal','Обычные рейсы',0],['reduced','Редкие рейсы',0]],rest:[['park','Парк',0],['gym','Спортцентр',0],['both','Оба места',1]],trigger:[['0','Сразу',1],['5','После 5 случаев',0],['10','После 10 случаев',0]]};
const defaults=()=>({school:'normal',work:'normal',shops:'both',bus:'normal',rest:'both',trigger:'5'});
function cost(plan){return Object.entries(choices).reduce((sum,[k,opts])=>{const opt=opts.find(o=>o[0]===plan[k]);if(!opt)throw Error('Выбери решение: '+k);return sum+opt[2];},0);}
function policy(plan){return {...M.policy(),school:plan.school,kindergarten:plan.school,work:plan.work,market:plan.shops==='mall'?'closed':'normal',mall:plan.shops==='market'?'closed':'normal',bus:plan.bus,park:plan.rest==='gym'?'closed':'normal',gym:plan.rest==='park'?'closed':'normal'};}
function run(plan,scenario=1,seed=1){const points=cost(plan);if(points>6)throw Error('План требует больше 6 очков.');if(![1,2].includes(scenario))throw Error('Неизвестный сценарий');let g=M.create({seed,districts:M.setup(),maxDays:90,initialDistrict:scenario===1?0:5,eventful:false,contactScale:.45,healthcareBeds:10}),activated=null;const first={day:0,phase:4,state:[...g.states],loc:g.people.map(p=>p.home),events:[],S:g.people.length-1,I:1,R:0,outside:0};
for(let day=1;day<=90;day++){const visible=g.states.filter(x=>x==='I'||x==='R').length;if(activated===null&&visible>=+plan.trigger)activated=day;g=M.step(g,activated===null?M.policy():policy(plan));if(!g.states.some(x=>x==='I'||x==='E'))break;}
const peak=Math.max(1,...g.reports.map(r=>r.infectious)),total=g.states.filter(x=>x!=='S').length,food=Math.round(g.reports.reduce((s,r)=>s+r.food,0)/g.day),activity=Math.round(g.reports.reduce((s,r)=>s+r.participation,0)/g.day);let streak=0,maxOverload=0;for(const r of g.reports){streak=r.unservedCare>0?streak+1:0;maxOverload=Math.max(maxOverload,streak);}const reasons=[];if(food<80)reasons.push(`Продукты: ${food}% вместо 80%`);if(activity<70)reasons.push(`Работа и учёба: ${activity}% вместо 70%`);if(maxOverload>3)reasons.push(`Больница перегружена ${maxOverload} дней подряд (можно до 3)`);if(g.states.some(x=>x==='E'||x==='I'))reasons.push('Вспышка не завершилась за 90 дней');return {plan:{...plan},points,scenario,seed,peak,total,food,activity,maxOverload,valid:!reasons.length,reasons,days:g.day,activated,history:[first,...g.history],people:g.people,districts:g.districts,reports:g.reports,policy:g.policy};}
function compare(a,b){return a.peak-b.peak||a.total-b.total;}
function final(first,second){return {valid:first.valid&&second.valid,peak:Math.max(first.peak,second.peak),total:Math.max(first.total,second.total),first,second};}
root.Contest={choices,defaults,cost,policy,run,compare,final};if(typeof module!=='undefined')module.exports=root.Contest;
})(typeof window!=='undefined'?window:globalThis);
