(function(root){'use strict';
const E=root.Epidemic||(typeof require==='function'?require('./epidemic.js'):null);
const modes={school:['normal','shifts','remote'],kindergarten:['normal','shifts','remote'],work:['normal','limited','remote','closed'],market:['normal','limited','long','closed'],mall:['normal','limited','long','closed'],bus:['normal','frequent','reduced','closed'],park:['normal','closed'],gym:['normal','limited','closed'],clinic:['normal','appointments','closed']};
const policy=()=>Object.fromEntries(Object.keys(modes).map(k=>[k,'normal']));
const events={4:{title:'Городская ярмарка',text:'Сегодня больше жителей хотят в торговый центр.',kind:'fair'},7:{title:'Похолодание',text:'Три дня жители предпочитают отдыхать в помещении.',kind:'cold'},8:{title:'Похолодание продолжается',text:'Жители по-прежнему выбирают помещения.',kind:'cold'},9:{title:'Последний холодный день',text:'Завтра парк снова будет привлекательнее.',kind:'cold'},10:{title:'Поломка автобуса',text:'Сегодня вместимость транспорта вдвое меньше.',kind:'bus'},12:{title:'Задержка поставки',text:'Сегодня маленький магазин обслужит вдвое меньше покупателей.',kind:'delivery'}};
function setup(profile='mixed'){return Array.from({length:6},(_,i)=>({adults:profile==='families'?8:profile==='older'?6:8,children:profile==='families'?8:profile==='older'?2:4,seniors:profile==='families'?1:profile==='older'?9:3,far:i===2||i===5}));}
function create({districts=setup(),seed=1,challenge='balance',maxDays=14,initialDistrict=0,eventful=true,contactScale=1,healthcareBeds=8}={}){const ds=districts.map(d=>({adults:Math.max(0,Math.min(20,+d.adults|0)),children:Math.max(0,Math.min(20,+d.children|0)),seniors:Math.max(0,Math.min(20,+d.seniors|0)),far:!!d.far}));if(ds.length!==6)throw Error('Нужно шесть кварталов');const people=ds.flatMap((d,k)=>['adults','children','seniors'].flatMap(type=>Array.from({length:d[type]},(_,i)=>({home:'h'+k,district:k,key:k*100+i+({adults:0,children:30,seniors:60}[type]),child:type==='children',preschool:type==='children'&&i%3===0,senior:type==='seniors'}))));if(!people.length)throw Error('Добавь жителей хотя бы в один квартал.');return {people,districts:ds,seed:+seed||1,challenge,maxDays,eventful,contactScale,healthcareBeds,day:0,cash:300,trust:85,states:people.map((p,i)=>i===people.findIndex(x=>x.district===initialDistrict)?'I':'S'),infected:people.map((p,i)=>i===people.findIndex(x=>x.district===initialDistrict)?0:null),exposed:people.map(()=>null),history:[],reports:[],decisions:[],policy:policy()};}
function event(day){return events[day]||{title:'Обычный день',text:'Посмотри на вчерашний отчёт и выбери, что изменить.',kind:'normal'};}
function step(game,choices){if(game.day>=(game.maxDays||14))throw Error('Две недели завершены');const g=JSON.parse(JSON.stringify(game)),p={...g.policy,...choices};for(const k of Object.keys(modes))if(!modes[k].includes(p[k]))throw Error('Неизвестный режим: '+k);const day=++g.day,ev=g.eventful===false?{title:'Обычный день',kind:'normal',text:''}:event(day),n=g.people.length,roll=(i,slot)=>E.rng(g.seed+g.people[i].key*1009+day*9176+slot*65537)(),random=E.rng(g.seed+day*131071),home=i=>g.people[i].home;let newCases=0;
for(let i=0;i<n;i++){if(g.states[i]==='E'&&day-g.exposed[i]>=2){g.states[i]='I';g.infected[i]=day;newCases++;}if(g.states[i]==='I'&&day-g.infected[i]>=6)g.states[i]='R';}
const infectious=g.states.filter(x=>x==='I').length,care=g.people.map((person,i)=>g.states[i]==='I'&&day-g.infected[i]>=1&&(person.senior||roll(i,20)<.3)?i:-1).filter(i=>i>=0),beds=g.healthcareBeds||8,treated=p.clinic==='closed'?0:Math.min(beds,care.length),careSet=new Set(care),careServed=new Set(care.slice(0,treated));
const caregivers=new Set();g.districts.forEach((d,k)=>{const kids=g.people.filter(x=>x.district===k&&x.child&&(p[x.preschool?'kindergarten':'school']==='remote')).length;g.people.map((x,i)=>({x,i})).filter(({x})=>x.district===k&&!x.child&&!x.senior).slice(0,Math.ceil(kids/2)).forEach(({i})=>caregivers.add(i));});
const dayLoc=g.people.map((person,i)=>{if(careSet.has(i))return home(i);if(person.child)return p[person.preschool?'kindergarten':'school']==='remote'?home(i):person.preschool?'kindergarten':'school';if(person.senior||caregivers.has(i)||p.work==='closed'||p.work==='remote')return home(i);return p.work==='limited'&&roll(i,1)>.5?home(i):'work';});
const commute=g.people.map((person,i)=>dayLoc[i]!==home(i)&&(g.districts[person.district].far||roll(i,2)<.4)?i:-1).filter(i=>i>=0),capacity=p.bus==='closed'?0:Math.floor((p.bus==='reduced'?20:p.bus==='frequent'?60:40)*(ev.kind==='bus'?.5:1)),missed=commute.slice(capacity),missedSet=new Set(missed);let missedFar=0;for(const i of missed)if(g.districts[g.people[i].district].far){dayLoc[i]=home(i);missedFar++;}
const shopLoc=g.people.map((person,i)=>{if(careSet.has(i))return p.clinic==='closed'?home(i):'clinic';if(person.child||roll(i,3)>.8)return home(i);const preferred=roll(i,4)<(ev.kind==='fair'?.8:.5)?'mall':'market',other=preferred==='mall'?'market':'mall';return p[preferred]!=='closed'?preferred:p[other]!=='closed'?other:home(i);});
const served=new Set();let queue=0;for(const place of ['market','mall']){const cap=Math.floor((place==='market'?22:40)*(p[place]==='limited'?.5:p[place]==='long'?1.5:1)*(place==='market'&&ev.kind==='delivery'?.5:1));const buyers=g.people.map((_,i)=>shopLoc[i]===place?i:-1).filter(i=>i>=0).sort((a,b)=>roll(a,8)-roll(b,8));buyers.slice(0,cap).forEach(i=>served.add(i));queue+=Math.max(0,buyers.length-cap);}
const restLoc=g.people.map((person,i)=>{if(careSet.has(i)||roll(i,5)>.7)return home(i);const preferred=ev.kind==='cold'?'gym':roll(i,6)<.65?'park':'gym';if(p[preferred]!=='closed')return preferred;for(const alt of ['park','gym','mall'])if(p[alt]!=='closed'&&(ev.kind!=='cold'||alt!=='park'))return alt;return home(i);});
let informal=0;for(let i=0;i<n;i++)if(restLoc[i]===home(i)&&roll(i,10)>(g.trust/100)&&roll(i,11)<.5){restLoc[i]='h'+((g.people[i].district+1)%6);informal++;}
const dayFrames=[],locations=[g.people.map((_,i)=>commute.includes(i)&&!missedSet.has(i)?'bus':home(i)),dayLoc,shopLoc,restLoc,g.people.map((_,i)=>home(i))];
for(let phase=0;phase<5;phase++){const loc=locations[phase],before=[...g.states],changes=[];for(let a=0;a<n;a++)for(let b=a+1;b<n;b++){const u=random();if(loc[a]!==loc[b])continue;const source=before[a]==='I'&&before[b]==='S'?a:before[b]==='I'&&before[a]==='S'?b:-1;if(source<0)continue;const target=source===a?b:a,id=loc[a];let factor=id[0]==='h'?.016:id==='park'?.003:.011;if(p[id]==='shifts')factor*=.5;if(p[id]==='limited')factor*=.75;if(p[id]==='long')factor*=.65;if(id==='clinic'&&p.clinic==='appointments')factor*=.5;if(id==='bus'&&p.bus==='reduced')factor*=1.4;if(id==='bus'&&p.bus==='frequent')factor*=.6;if(u<factor*(g.contactScale??1)&&g.states[target]==='S'){g.states[target]='E';g.exposed[target]=day;changes.push({source,target,place:id});}}
const state=g.states.map(x=>x==='E'?'S':x);dayFrames.push({day,phase,state,loc,events:[],S:state.filter(x=>x==='S').length,I:state.filter(x=>x==='I').length,R:state.filter(x=>x==='R').length,outside:loc.filter(x=>x[0]!=='h').length});}
const districtReports=g.districts.map((d,k)=>{const ids=g.people.map((x,i)=>x.district===k?i:-1).filter(i=>i>=0),food=Math.min(ids.length,ids.filter(i=>served.has(i)).length*3),rest=ids.filter(i=>restLoc[i]!==home(i)).length,students=ids.filter(i=>g.people[i].child),education=students.reduce((v,i)=>v+(dayLoc[i]!==home(i)?1:p[g.people[i].preschool?'kindergarten':'school']==='remote'?.6:0),0);return {district:k,population:ids.length,food,rest,education,students:students.length,missed:ids.filter(i=>missedSet.has(i)&&d.far).length,ill:ids.filter(i=>g.states[i]==='I').length};});
const food=100*districtReports.reduce((v,d)=>v+d.food,0)/n,rest=100*restLoc.filter((id,i)=>id!==home(i)).length/n,students=districtReports.reduce((v,d)=>v+d.students,0),education=students?100*districtReports.reduce((v,d)=>v+d.education,0)/students:100,workers=dayLoc.filter(id=>id==='work').length+g.people.filter((person,i)=>!person.child&&!person.senior&&!caregivers.has(i)&&!careSet.has(i)&&p.work==='remote'&&roll(i,31)<.6).length,income=workers*3+served.size,expenses=30+(p.clinic==='closed'?0:18)+(p.bus==='closed'?0:p.bus==='reduced'?6:12)+['school','kindergarten'].reduce((v,k)=>v+(p[k]==='remote'?3:p[k]==='shifts'?14:8),0)+['market','mall'].filter(k=>p[k]==='long').length*8;
g.cash+=income-expenses;const unservedCare=care.length-treated,trustCauses={food:Math.round((food-85)/22),rest:Math.round((rest-40)/20),education:Math.round((education-85)/35),care:-Math.ceil(unservedCare*.6),transport:-Math.ceil(missedFar*.15),debt:g.cash<0?-2:0},requestedDelta=Object.values(trustCauses).reduce((a,b)=>a+b,0),oldTrust=g.trust;g.trust=Math.max(0,Math.min(100,g.trust+requestedDelta));const delta=g.trust-oldTrust;
const report={day,event:ev,infectious,newCases,care:care.length,treated,beds,unservedCare,cash:g.cash,income,expenses,trust:g.trust,trustDelta:delta,trustCauses,food:Math.round(food),rest:Math.round(rest),education:Math.round(education),queue,workers,participation:Math.round(100*(workers+districtReports.reduce((v,d)=>v+d.education,0))/Math.max(1,g.people.filter(x=>!x.senior).length)),caregivers:caregivers.size,missed:missedFar,informal,districts:districtReports,policy:{...p},counts:Object.fromEntries(['market','mall','park','gym','bus'].map(id=>[id,Math.max(...locations.map(ls=>ls.filter(x=>x===id).length))]))};g.history.push(...dayFrames);g.reports.push(report);g.policy=p;g.decisions.push({day,policy:{...p}});return g;}
root.Mayor={create,step,event,setup,policy,modes};if(typeof module!=='undefined')module.exports=root.Mayor;
})(typeof window!=='undefined'?window:globalThis);
