/* The city scene is a view of TrafficEngine agents, never an extra traffic simulator. */
(function(root){
  'use strict';
  const NS='http://www.w3.org/2000/svg';
  const layout={width:1400,height:720,y:360,junctions:{A:330,B:700,C:1070}};
  const palette=['#dc9565','#5d9ea5','#668bb9','#a789b5','#d2af66','#779c72'];
  function el(tag,attrs={},text){const node=document.createElementNS(NS,tag);for(const [key,value]of Object.entries(attrs))node.setAttribute(key,value);if(text!==undefined)node.textContent=text;return node;}
  function add(parent,tag,attrs={},text){const node=el(tag,attrs,text);parent.append(node);return node;}
  function text(parent,value,x,y,size=20,attrs={}){return add(parent,'text',{x,y,'font-size':size,'font-family':'system-ui, sans-serif','font-weight':650,fill:'#314b43','text-anchor':'middle',...attrs},value);}
  function line(parent,d,stroke,width,attrs={}){return add(parent,'path',{d,fill:'none',stroke,'stroke-width':width,'stroke-linecap':'round',...attrs});}
  function tree(parent,x,y,size=1){const g=add(parent,'g',{transform:`translate(${x} ${y}) scale(${size})`,'aria-hidden':'true'});add(g,'ellipse',{cx:4,cy:16,rx:20,ry:7,fill:'#607c60',opacity:.18});line(g,'M0 9V22','#8c8061',5);add(g,'ellipse',{cx:0,cy:-5,rx:18,ry:22,fill:'#67946c'});add(g,'ellipse',{cx:-7,cy:-9,rx:12,ry:17,fill:'#7dab76'});add(g,'ellipse',{cx:6,cy:-17,rx:10,ry:12,fill:'#92b77e'});}
  function scenery(svg){
    const defs=add(svg,'defs');
    const grass=add(defs,'linearGradient',{id:'traffic-grass',x2:'0%',y2:'100%'});add(grass,'stop',{offset:0,'stop-color':'#e0ebcd'});add(grass,'stop',{offset:1,'stop-color':'#c5d9bc'});
    const water=add(defs,'linearGradient',{id:'traffic-water',x2:'100%',y2:'40%'});add(water,'stop',{offset:0,'stop-color':'#94c9cd'});add(water,'stop',{offset:1,'stop-color':'#68aebd'});
    const asphalt=add(defs,'pattern',{id:'traffic-asphalt',width:36,height:36,patternUnits:'userSpaceOnUse'});add(asphalt,'rect',{width:36,height:36,fill:'#657e81'});for(const [x,y]of[[3,12],[15,5],[25,23],[8,29],[30,8]])add(asphalt,'circle',{cx:x,cy:y,r:.7,fill:'#8ea1a0',opacity:.55});
    const lawn=add(defs,'pattern',{id:'traffic-lawn',width:66,height:56,patternUnits:'userSpaceOnUse'});for(const [x,y]of[[4,15],[26,35],[48,10]])line(lawn,`M${x} ${y}l2-4m-2 4-2-3`,'#83a581',.8,{opacity:.4});
    const paving=add(defs,'pattern',{id:'traffic-paving',width:24,height:16,patternUnits:'userSpaceOnUse'});add(paving,'rect',{width:24,height:16,fill:'#e1dbbf'});line(paving,'M0 0H24M0 8H24M12 0V8M0 8V16M24 8V16','#d1cbb1',1);
    const filter=add(defs,'filter',{id:'traffic-shadow',x:'-25%',y:'-25%',width:'150%',height:'160%'});add(filter,'feDropShadow',{dx:0,dy:3,stdDeviation:3,'flood-color':'#365948','flood-opacity':'.2'});
    const marker=add(defs,'marker',{id:'traffic-arrow',markerWidth:8,markerHeight:8,refX:6,refY:4,orient:'auto',markerUnits:'userSpaceOnUse'});add(marker,'path',{d:'M1 1L7 4 1 7',fill:'none',stroke:'#e8e6d0','stroke-width':2});
    const background=add(svg,'g',{class:'traffic-scenery','aria-hidden':'true','pointer-events':'none'});
    add(background,'rect',{width:1400,height:720,rx:24,fill:'url(#traffic-grass)'});add(background,'rect',{width:1400,height:720,rx:24,fill:'url(#traffic-lawn)'});
    line(background,'M1360-20C1280 96 1301 223 1335 334S1339 523 1300 610 1324 747 1357 762','#b7d3bd',116);
    line(background,'M1360-20C1280 96 1301 223 1335 334S1339 523 1300 610 1324 747 1357 762','url(#traffic-water)',92);
    for(const [x,y]of[[1326,73],[1328,202],[1360,473],[1319,617]])line(background,`M${x-20} ${y}q12-5 28 0m-15 13q12-5 28 0`,'#d1e9df',2,{opacity:.65});
    // Courtyards stay outside roads and their live queues.
    const xs=Object.values(layout.junctions),blocks=[],edges=[0,...xs,1400];for(let n=0;n<edges.length-1;n++){const left=edges[n]+(n?72:20),right=edges[n+1]-(n===edges.length-2?20:72);blocks.push({x:left,width:Math.max(80,right-left)});}const lots=blocks.flatMap(b=>[{...b,y:43},{...b,y:519}]);
    for(const p of lots){add(background,'rect',{x:p.x,y:p.y,width:p.width,height:177,rx:24,fill:'#b9cda7',stroke:'#a4bd97','stroke-width':2});add(background,'rect',{x:p.x+8,y:p.y+108,width:p.width-16,height:58,rx:12,fill:'url(#traffic-paving)'});line(background,`M${p.x+p.width/2} ${p.y+158}V${p.y<300?272:504}`,'#dddac0',14);}
    const roads=add(background,'g',{class:'traffic-roads'});
    for(let n=0;n<xs.length-1;n++){const exitX=(xs[n]+xs[n+1])/2;line(roads,`M${exitX} 188V298`,'url(#traffic-paving)',36);line(roads,`M${exitX} 190V292`,'url(#traffic-asphalt)',24);line(roads,`M${exitX} 422V533`,'url(#traffic-paving)',36);line(roads,`M${exitX} 428V530`,'url(#traffic-asphalt)',24);line(roads,`M${exitX-8} 482v20`,'#bbc9bf',1.5,{'marker-end':'url(#traffic-arrow)'});}line(roads,'M20 360H1380','#9ab099',154);line(roads,'M20 360H1380','url(#traffic-paving)',144);line(roads,'M20 360H1380','#455e65',120);line(roads,'M20 360H1380','url(#traffic-asphalt)',112);
    for(const x of Object.values(layout.junctions)){line(roads,`M${x} 15V705`,'#9ab099',136);line(roads,`M${x} 15V705`,'url(#traffic-paving)',128);line(roads,`M${x} 15V705`,'#455e65',106);line(roads,`M${x} 15V705`,'url(#traffic-asphalt)',100);}
    // A bridge has railings, but exactly the same usable lanes as the main road.
    line(background,'M1272 291H1377','#e3d7ba',9);line(background,'M1272 429H1377','#e3d7ba',9);for(let x=1275;x<1380;x+=22){line(background,`M${x} 284V300`,'#b5a791',3);line(background,`M${x} 422V437`,'#b5a791',3);}
    for(let n=0;n<=xs.length;n++){const a=n?xs[n-1]+87:25,b=n<xs.length?xs[n]-87:1375;if(b>a)line(roads,`M${a} 360H${b}`,'#ece6c7',3,{'stroke-dasharray':'12 13'});}
    for(const x of Object.values(layout.junctions)){
      line(roads,`M${x} 15V274M${x} 446V705`,'#e7dcab',3,{'stroke-dasharray':'12 13'});
      // Crossing stripes, stop lines and arrows make both streams legible.
      for(let n=0;n<6;n++){add(roads,'rect',{x:x-45+n*17,y:279,width:9,height:19,rx:1,fill:'#f0eddb',opacity:.92});add(roads,'rect',{x:x-45+n*17,y:422,width:9,height:19,rx:1,fill:'#f0eddb',opacity:.92});add(roads,'rect',{x:x-82,y:309+n*17,width:19,height:9,rx:1,fill:'#f0eddb',opacity:.92});add(roads,'rect',{x:x+63,y:309+n*17,width:19,height:9,rx:1,fill:'#f0eddb',opacity:.92});}
      line(roads,`M${x-94} 365V409M${x+94} 310V355M${x-43} 265H${x-5}M${x+5} 455H${x+43}`,'#f0eddb',5,{'stroke-linecap':'butt'});
      line(roads,`M${x-165} 385h27M${x+165} 335h-27M${x-25} 183v27M${x+25} 537v-27`,'#d0d9cd',2,{'marker-end':'url(#traffic-arrow)',opacity:.85});
      line(roads,`M${x-49} 32V270M${x-49} 450V698`,'#b7ba9e',1.5,{'stroke-dasharray':'2 5',opacity:.6});
      // Bus stop shelters and decorative benches are never traffic agents.
      for(const y of [245,470]){add(background,'rect',{x:x-72,y,width:15,height:35,rx:3,fill:'#e7e2c8',stroke:'#7e9c8a','stroke-width':2});line(background,`M${x-68} ${y+7}v21`,'#88a797',3);}
    }
    const buildings=add(background,'g',{class:'traffic-buildings'});
    const north=[['h0','Дома'],['h1','Тихие дворы'],['school','Школа'],['clinic','Поликлиника'],['gym','Спортцентр']],south=[['h3','Жилой квартал'],['h4','Южные дома'],['market','Магазины'],['work','Работа'],['park','Парк']];
    for(let n=0;n<blocks.length;n++)for(const upper of[true,false]){const p=blocks[n],spec=(upper?north:south)[n],id=spec[0],name=spec[1],w=Math.min(176,p.width-12),h=Math.min(166,w*1.07),x=p.x+(p.width-w)/2,y=upper?210-h:688-h;add(buildings,'ellipse',{cx:x+w/2,cy:y+h-5,rx:w*.42,ry:13,fill:'#536c58',opacity:.17});const fallback=add(buildings,'g',{class:'traffic-building-fallback'});add(fallback,'rect',{x:x+20,y:y+35,width:w-40,height:h-42,rx:9,fill:'#eadabb',stroke:'#ad9d83','stroke-width':2});add(fallback,'path',{d:`M${x+13} ${y+50}L${x+w/2} ${y+12} ${x+w-13} ${y+50}Z`,fill:'#839e96'});const img=add(buildings,'image',{class:'traffic-building',href:`assets/buildings/${id}.webp`,x,y,width:w,height:h,preserveAspectRatio:'xMidYMax meet','data-place':id});img.onload=()=>fallback.remove();img.onerror=()=>img.remove();text(buildings,name,x+w/2,upper?27:712,18,{class:'traffic-place-label',fill:'#567056','font-weight':650});tree(background,p.x+10,upper?78:548,.7);if(p.width>140)tree(background,p.x+p.width-9,upper?207:660,.8);if(p.width>250){tree(background,p.x+38,upper?177:653,.8);tree(background,p.x+p.width-35,upper?102:555,.8);}if(!upper)tree(background,p.x+p.width/2+32,492,.55);}
    return background;
  }
  function control(parent,junction,axis,x,y,onSelect){
    const g=add(parent,'g',{class:'traffic-axis',transform:`translate(${x} ${y})`,'data-junction':junction,'data-axis':axis,tabindex:0,role:'button','aria-pressed':'false'});
    add(g,'rect',{class:'traffic-axis-bg',width:64,height:64,rx:16,fill:'#fdf9e9',stroke:'#b2c4ae','stroke-width':2});text(g,axis==='EW'?'↔':'↕',32,43,39,{class:'traffic-axis-arrow',fill:axis==='EW'?'#548bae':'#9372b5'});
    g.onclick=()=>{if(g.getAttribute('aria-disabled')!=='true')onSelect?.(junction,axis);};g.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&g.getAttribute('aria-disabled')!=='true'){e.preventDefault();onSelect?.(junction,axis);}};return g;
  }
  function signal(parent,junction,axis,dir,x,y){
    const g=add(parent,'g',{class:'traffic-signal',transform:`translate(${x} ${y})`,'data-junction':junction,'data-axis':axis,'data-dir':dir,role:'img'});
    add(g,'title');line(g,'M12 49V64','#728575',3);add(g,'rect',{width:24,height:50,rx:8,fill:'#526f64',stroke:'#3c5b50','stroke-width':2});const lamps={};for(const[color,cy]of[['red',10],['yellow',25],['green',40]])lamps[color]=add(g,'circle',{class:'traffic-lamp traffic-lamp-'+color,cx:12,cy,r:6.5,fill:'#34594d',stroke:'#274e42','stroke-width':1});return {g,lamps};
  }
  function agentView(parent,agent,onAgent){
    const g=add(parent,'g',{class:'traffic-agent','data-agent-id':agent.id,role:'button',tabindex:0,'aria-label':'Участник движения'});add(g,'title');const ring=add(g,'ellipse',{class:'traffic-agent-ring',rx:35,ry:24,fill:'none',stroke:'#f5b760','stroke-width':3,opacity:0});const body=add(g,'g',{class:'traffic-agent-body'});
    const index=String(agent.id).split('').reduce((n,c)=>n+c.charCodeAt(0),0),color=palette[index%palette.length];
    if(agent.kind==='pedestrian'){
      const people=Math.min(4,Math.max(1,agent.people||1));for(let n=0;n<people;n++){const x=(n%2-.5)*13,y=Math.floor(n/2)*12-8;add(body,'ellipse',{cx:x+1,cy:y+12,rx:5,ry:2,fill:'#436154',opacity:.25});line(body,`M${x-2} ${y+8}v5m4-5v5`,'#475f60',2);add(body,'rect',{x:x-4,y:y-1,width:8,height:11,rx:3,fill:palette[(index+n)%palette.length]});add(body,'circle',{cx:x,cy:y-5,r:4,fill:'#f2cda7'});}
    }else{
      const bus=agent.kind==='bus',width=bus?65:43,height=bus?27:23;add(body,'ellipse',{cx:2,cy:4,rx:width/2,ry:height/2,fill:'#334e49',opacity:.23});for(const x of[-width/2+9,width/2-9])for(const y of[-height/2,height/2-4])add(body,'rect',{x:x-5,y,width:10,height:5,rx:2,fill:'#345657'});add(body,'rect',{x:-width/2,y:-height/2,width,height,rx:bus?7:9,fill:bus?'#eec46c':color,stroke:bus?'#a99256':'#537574','stroke-width':1.5});add(body,'rect',{x:width/2-(bus?11:13),y:-height/2+4,width:bus?6:8,height:height-8,rx:2,fill:'#d5e5dd'});add(body,'rect',{x:-width/2+7,y:-height/2+4,width:bus?width-25:15,height:height-8,rx:3,fill:'#507782'});if(bus){for(let x=-width/2+11;x<width/2-15;x+=9)line(body,`M${x} ${-height/2+4}V${height/2-4}`,'#b7d5ca',1);add(body,'rect',{x:-width/2+10,y:-2,width:width-25,height:4,rx:2,fill:'#e8bc68'});}else{add(body,'circle',{cx:3,cy:-4,r:2.5,fill:'#f1c4a0'});if(agent.people>1)add(body,'circle',{cx:3,cy:4,r:2.5,fill:'#f1c4a0'});}for(const y of[-height/2+3,height/2-6])add(body,'rect',{x:width/2-3,y,width:3,height:3,rx:1,fill:'#fff1b8'});
    }
    const badge=add(g,'g',{class:'traffic-agent-badge'});const badgeBg=add(badge,'rect',{x:-19,y:-42,width:38,height:24,rx:9,fill:'#fff4cd',stroke:'#afaa86','stroke-width':1.5});const number=text(badge,String(agent.people||1),0,-24,18,{class:'traffic-agent-count',fill:'#43594c'});const clock=text(g,'',0,39,17,{class:'traffic-agent-deadline',fill:'#963c32','font-weight':750});
    g.onclick=()=>onAgent?.(agent.id);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onAgent?.(agent.id);}};return {g,body,ring,badge,badgeBg,number,clock};
  }
  function finite(value,fallback=0){return Number.isFinite(value)?value:fallback;}
  function direction(part){return part?.dir===-1?-1:1;}
  function directionName(axis,dir){return axis==='EW'?(Number(dir)===1?'слева направо':'справа налево'):(Number(dir)===1?'сверху вниз':'снизу вверх');}
  function streamKey(junction,axis,dir){return junction+'|'+axis+'|'+dir;}
  function queuePositions(state){
    const streams={};for(const a of state.agents||[])if(a.status==='queued'){const part=a.route?.[a.leg]||a.to||a.from;if(!part||!layout.junctions[part.junction])continue;const key=streamKey(part.junction,part.axis,direction(part))+(a.kind==='pedestrian'?'|walk':'|road');(streams[key]||(streams[key]=[])).push(a);}
    const positions=new Map(),xs=Object.values(layout.junctions);
    for(const agents of Object.values(streams)){agents.sort((a,b)=>finite(a.queuePosition)-finite(b.queuePosition)||finite(a.order)-finite(b.order));const part=agents[0].route?.[agents[0].leg]||agents[0].to||agents[0].from,x=layout.junctions[part.junction],dir=direction(part),adjacent=xs[xs.indexOf(x)-dir];let offset=0,full=false;const limit=part.axis==='NS'?218:adjacent?Math.abs(x-adjacent)-156:dir===1?x-112:1400-x-112;
      for(const a of agents){const size=a.kind==='bus'?70:a.kind==='pedestrian'?37:49;if(full||offset+size>limit){positions.set(a.id,{hidden:true,junction:part.junction,axis:part.axis,dir});full=true;continue;}const center=offset+size/2,ped=a.kind==='pedestrian';positions.set(a.id,{x:part.axis==='EW'?x-dir*(82+center):x+(ped?dir*62:-dir*25),y:part.axis==='NS'?360-dir*(84+center):ped?(dir===1?433:287):(dir===1?385:335),rotation:ped?0:part.axis==='NS'?dir*90:dir===1?0:180,dir});offset+=size;}
    }return positions;
  }
  function position(agent,queued,state){
    if(agent.status==='queued')return queued.get(agent.id);
    const from=agent.from||agent.route?.[Math.max(0,agent.leg-1)]||agent.route?.[0]||{junction:'A',axis:'EW',dir:1},to=agent.to||agent.route?.[agent.leg],cx=layout.junctions[from.junction]||330,axis=from.axis||'EW',dir=direction(from),p=Math.max(0,Math.min(1,finite(agent.progress))),ped=agent.kind==='pedestrian',rotation=ped?0:axis==='NS'?dir*90:dir===1?0:180;
    if(axis==='NS'){const start=360-dir*108,end=dir===1?710:10;return{x:cx+(ped?dir*62:-dir*25),y:start+(end-start)*p,rotation,dir};}
    const xs=Object.values(layout.junctions),adjacent=xs[xs.indexOf(cx)+dir],start=cx-dir*108,y=ped?(dir===1?433:287):(dir===1?385:335);
    if(!to?.junction&&adjacent){const target=(cx+adjacent)/2,endY=dir===1?525:220,u=1-p;return{x:u*u*u*start+3*u*u*p*(start+dir*100)+3*u*p*p*target+p*p*p*target,y:u*u*u*y+3*u*u*p*y+3*u*p*p*endY+p*p*p*endY,rotation:ped?0:rotation+90*p,dir};}
    let end=dir===1?1380:20;
    if(to?.junction){end=(layout.junctions[to.junction]||cx+dir*320)-dir*108;const ahead=(state.agents||[]).filter(a=>a.status==='queued'&&a.route?.[a.leg]?.junction===to.junction&&a.route[a.leg].axis===axis&&direction(a.route[a.leg])===dir&&(a.kind==='pedestrian')===ped);for(const a of ahead){const q=queued.get(a.id);if(q&&!q.hidden){const tail=q.x-dir*((a.kind==='bus'?38:25)+(agent.kind==='bus'?38:25));end=dir===1?Math.min(end,tail):Math.max(end,tail);}}
      const reserved=(state.agents||[]).filter(a=>a.status==='moving'&&a.id!==agent.id&&a.to?.junction===to.junction&&a.to.axis===axis&&direction(a.to)===dir&&(a.kind==='pedestrian')===ped&&(finite(a.departedAt)<finite(agent.departedAt)||a.departedAt===agent.departedAt&&finite(a.order)<finite(agent.order)));end-=dir*reserved.reduce((n,a)=>n+(a.kind==='bus'?70:49),0);const clearance=agent.kind==='bus'?85:65;end=dir===1?Math.max(cx+clearance,end):Math.min(cx-clearance,end);
    }return{x:start+(end-start)*p,y,rotation,dir};
  }
  function vehicleBounds(agent,p){
    const width=agent.kind==='bus'?65:43,height=agent.kind==='bus'?27:23,angle=p.rotation*Math.PI/180,cos=Math.cos(angle),sin=Math.sin(angle),corners=[[-width/2,-height/2],[width/2+2,-height/2],[-width/2,height/2+4],[width/2+2,height/2+4]].map(([x,y])=>[p.x+x*cos-y*sin,p.y+x*sin+y*cos]);return{left:Math.min(...corners.map(c=>c[0])),right:Math.max(...corners.map(c=>c[0])),top:Math.min(...corners.map(c=>c[1])),bottom:Math.max(...corners.map(c=>c[1]))};
  }
  function conflicts(a,b){return Math.min(a.right,b.right)-Math.max(a.left,b.left)>-3&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>-3;}
  function tripKey(agent){return agent.id+'|'+agent.leg+'|'+agent.departedAt;}
  function visibleTraffic(state,queued,aggregatedTrips){
    const result=new Map(queued),occupied=[];for(const agent of state.agents||[])if(agent.status==='queued'&&agent.kind!=='pedestrian'){const p=queued.get(agent.id);if(p&&!p.hidden)occupied.push(vehicleBounds(agent,p));}
    const moving=(state.agents||[]).filter(a=>a.status==='moving').sort((a,b)=>b.progress-a.progress||finite(a.departedAt)-finite(b.departedAt)||finite(a.order)-finite(b.order)),activeTrips=new Set(moving.map(tripKey));for(const key of aggregatedTrips)if(!activeTrips.has(key))aggregatedTrips.delete(key);
    for(const agent of moving){const p=position(agent,queued,state),key=tripKey(agent),box=agent.kind==='pedestrian'?null:vehicleBounds(agent,p),blocked=aggregatedTrips.has(key)||box&&occupied.some(other=>conflicts(box,other));if(blocked){aggregatedTrips.add(key);result.set(agent.id,{hidden:true,moving:true,junction:agent.from.junction,axis:agent.from.axis,dir:direction(agent.from)});}else {result.set(agent.id,p);if(box)occupied.push(box);}}
    return result;
  }
  function tailView(parent,junction,axis,dir,x,y,onAgent){
    const g=add(parent,'g',{class:'traffic-queue-tail',transform:`translate(${x-42} ${y})`,'data-junction':junction,'data-axis':axis,'data-dir':dir,display:'none',role:'button',tabindex:-1});add(g,'rect',{width:84,height:64,fill:'transparent'});const bottom=axis==='NS'&&dir===-1,bg=add(g,'rect',{x:2,y:bottom?22:1,width:80,height:21,rx:9,fill:'#f7f1dd',stroke:'#aabb9f','stroke-width':1}),label=text(g,'',42,bottom?38:17,17,{class:'traffic-tail-count',fill:'#58755d'}),moving=add(g,'g',{class:'traffic-moving-tail','data-junction':junction,'data-axis':axis,'data-dir':dir,display:'none'}),movingLabel=text(moving,'',42,bottom?58:37,17,{class:'traffic-tail-moving-count',fill:'#55788c'});g.onclick=()=>onAgent?.(g.dataset.agentId);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onAgent?.(g.dataset.agentId);}};return{g,bg,label,moving,movingLabel,bottom};
  }
  function crashView(parent,junction,x){
    const g=add(parent,'g',{class:'traffic-crash','data-junction':junction,'aria-hidden':'true',opacity:0});
    const smoke=add(g,'g',{class:'traffic-crash-smoke'});for(const[cx,cy,r]of[[-25,-7,17],[9,-24,22],[36,-10,16],[-8,7,23],[22,8,20]])add(smoke,'circle',{cx:x+cx,cy:360+cy,r,fill:'#d7dfd4',stroke:'#a9b9aa','stroke-width':1.5,opacity:.88});
    for(const [dx,dy,rotation]of[[-35,-28,-20],[37,-31,15],[33,30,5]])add(g,'path',{d:'M0-14 4-5 13-7 7 1 13 8 3 7 0 16-4 6-14 8-8 0-13-7-4-5Z',transform:`translate(${x+dx} ${360+dy}) rotate(${rotation})`,fill:'#f6d36c',stroke:'#d99552','stroke-width':2});
    for(const[dx,dy]of[[-73,24],[-23,-87],[30,-87]]){add(g,'path',{d:`M${x+dx-9} ${360+dy+13}l9-23 9 23Z`,fill:'#ecad6e',stroke:'#b77649','stroke-width':2});line(g,`M${x+dx-5} ${360+dy+4}h10`,'#fff1cc',3);}
    add(g,'rect',{x:x-99,y:307,width:198,height:31,rx:10,fill:'#fff0cd',stroke:'#d49b61','stroke-width':2});const title=text(g,'СТОЛКНОВЕНИЕ',x,329,18,{class:'traffic-crash-label',fill:'#965b38'});return {g,smoke,title};
  }
  function configure(ids){const positions=ids.length===2?[465,945]:ids.length===4?[260,580,900,1220]:[330,700,1070];layout.junctions=Object.fromEntries(ids.map((id,n)=>[id,positions[n]]));}
  function init(svg,{onSelect,onAgent}={}){
    let junctions={},agentLayer,views=new Map(),aggregatedTrips=new Set(),previousTick=-1,previousScenario=null,activeIds='',animationFrame=0,animationEnabled=false,lastFrameTime=0,previousRenderTime=0;
    function stopAnimation(){if(animationFrame)root.cancelAnimationFrame(animationFrame);animationFrame=0;}
    function rebuild(ids){stopAnimation();activeIds=ids.join('|');configure(ids);svg.replaceChildren();views.clear();aggregatedTrips.clear();svg.setAttribute('viewBox','0 0 1400 720');svg.setAttribute('role','group');svg.setAttribute('aria-label',`Город: ${ids.length} перекрёстка, настоящие очереди и светофоры`);scenery(svg);junctions={};const junctionLayer=add(svg,'g',{class:'traffic-junctions'});
      for(const [id,x]of Object.entries(layout.junctions)){
        const group=add(junctionLayer,'g',{class:'traffic-junction','data-junction':id}),preview=add(group,'g',{class:'traffic-green-preview','pointer-events':'none','aria-hidden':'true'}),ewPreview=line(preview,`M${x-53} 335H${x+54}M${x-53} 385H${x+54}`,'#8ac99b',11,{opacity:0,'stroke-dasharray':'7 5'}),nsPreview=line(preview,`M${x-25} 307V413M${x+25} 307V413`,'#8ac99b',11,{opacity:0,'stroke-dasharray':'7 5'});
        add(group,'circle',{cx:x-236,cy:267,r:19,fill:'#e8eed5',stroke:'#9db494','stroke-width':2});text(group,id,x-236,275,22,{class:'traffic-junction-label',fill:'#527052'});const ew=control(group,id,'EW',x-208,234,onSelect),ns=control(group,id,'NS',x-137,234,onSelect),signals={
          'EW|1':signal(group,id,'EW',1,x-99,427),'EW|-1':signal(group,id,'EW',-1,x+75,238),
          'NS|1':signal(group,id,'NS',1,x-70,226),'NS|-1':signal(group,id,'NS',-1,x+46,444)
        },timer=text(group,'',x-236,308,17,{class:'traffic-signal-time',fill:'#446659','font-weight':750}),blocked=add(group,'g',{class:'traffic-storage-blocked','aria-hidden':'true',opacity:0}),blockDirs={};
        for(const dir of[1,-1]){const g=add(blocked,'g',{class:'traffic-blocked-direction','data-dir':dir,opacity:0});line(g,`M${x-dir*88} ${dir===1?368:318}v33`,'#cc8b65',5);blockDirs[dir]=g;}
        const xs=Object.values(layout.junctions),previous=xs[xs.indexOf(x)-1],next=xs[xs.indexOf(x)+1],tails={};
        for(const axis of['EW','NS'])for(const dir of[1,-1]){const tx=axis==='NS'?x-dir*25:dir===1?(previous?previous+132:62):(next?next-145:1338),ty=axis==='NS'?(dir===1?1:656):(dir===1?418:476);tails[axis+'|'+dir]=tailView(group,id,axis,dir,tx,ty,onAgent);}
        junctions[id]={group,ew,ns,signals,timer,ewPreview,nsPreview,blocked,blockDirs,tails};
      }
      agentLayer=add(svg,'g',{class:'traffic-agents'});const crashLayer=add(svg,'g',{class:'traffic-crashes','pointer-events':'none'});for(const[id,x]of Object.entries(layout.junctions))junctions[id].crash=crashView(crashLayer,id,x);
    }
    function paint(view,p){view.current=p;view.g.setAttribute('transform',`translate(${p.x.toFixed(2)} ${p.y.toFixed(2)})`);view.body.setAttribute('transform',`rotate(${p.rotation}) scale(${p.scale||1})`);}
    function frame(now){animationFrame=0;if(!animationEnabled)return;let moving=false;for(const [id,view]of views){if(!view.tween)continue;const t=Math.min(1,(now-view.tween.time)/view.tween.duration),a=view.tween.from,b=view.tween.to;paint(view,{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,rotation:a.rotation+(b.rotation-a.rotation)*t,scale:(a.scale||1)+((b.scale||1)-(a.scale||1))*t});if(view.departing)view.g.setAttribute('opacity',String(1-t));if(t<1)moving=true;else {view.tween=null;if(view.departing){view.g.remove();views.delete(id);}}}let hazards=false;for(const j of Object.values(junctions)){if(Number(j.crash.g.getAttribute('opacity'))>0){hazards=true;j.crash.smoke.setAttribute('transform',`translate(0 ${Math.sin(now/350)*3})`);}}if(moving||hazards)animationFrame=root.requestAnimationFrame(frame);}
    rebuild(['A','B','C']);
    function render(state,options={}){
      const ids=state.junctionIds||Object.keys(state.signals||{});if(ids.join('|')!==activeIds)rebuild(ids);const now=root.performance?.now()||Date.now(),changed=state.scenarioId!==previousScenario||state.tick!==previousTick,interval=previousRenderTime?Math.min(400,Math.max(70,now-previousRenderTime)):0;if(changed)previousRenderTime=now;animationEnabled=options.animate===true&&!options.reducedMotion;if(!animationEnabled)stopAnimation();const selectedJunction=options.selectedJunction,selectedAxis=options.selectedAxis,preview=options.ghost===true;if(state.scenarioId!==previousScenario||state.tick<previousTick)aggregatedTrips.clear();previousScenario=state.scenarioId;previousTick=finite(state.tick);
      for(const [id,j]of Object.entries(junctions)){const signalState=state.signals?.[id]||{},clearance=finite(signalState.clearance),blockedSeconds=Math.max(0,finite(signalState.blockedUntil)-finite(state.tick)),active=clearance>0||blockedSeconds>0?null:signalState.axis;
        const disc=j.group.querySelector('circle');disc.setAttribute('fill',id===selectedJunction?'#f0dfad':'#e8eed5');
        for(const[axis,controlNode]of[['EW',j.ew],['NS',j.ns]]){const disabled=options.interactive===false||(options.teaching===true&&id!==selectedJunction),selected=id===selectedJunction&&(axis===selectedAxis||selectedAxis==='BOTH');controlNode.setAttribute('aria-disabled',String(disabled));controlNode.setAttribute('tabindex',disabled?-1:0);controlNode.setAttribute('opacity',disabled?.4:1);controlNode.style.cursor=disabled?'default':'pointer';controlNode.setAttribute('aria-label',`Перекрёсток ${id}: ${axis==='EW'?'дорога слева направо и справа налево':'улица сверху вниз и снизу вверх'} — ${options.teaching===false?'посмотреть потоки':'выбрать зелёный'}`);controlNode.classList.toggle('is-selected',selected);controlNode.setAttribute('aria-pressed',String(selected));const rect=controlNode.querySelector('rect');rect.setAttribute('fill',selected?(axis==='EW'?'#e1eef5':'#eee5f4'):'#fdf9e9');rect.setAttribute('stroke',selected?(axis==='EW'?'#548bae':'#9372b5'):'#b2c4ae');rect.setAttribute('stroke-width',selected?3:2);}
        for(const[key,light]of Object.entries(j.signals)){const axis=key.split('|')[0],green=active===axis||active==='BOTH',color=green?'green':clearance>0?'yellow':'red';light.g.classList.toggle('is-green',green);light.g.classList.toggle('is-clearance',clearance>0);for(const[c,lamp]of Object.entries(light.lamps)){lamp.setAttribute('fill',c===color?c==='green'?'#7ad29b':c==='yellow'?'#f0cd72':'#e4907e':'#365b4e');lamp.setAttribute('stroke',c===color?'#dce4c8':'#274e42');}light.g.setAttribute('aria-label',`${id}: ${axis==='EW'?'дорога':'улица'}, ${directionName(axis,light.g.dataset.dir)} — ${green?'зелёный':clearance>0?'жёлтый':'красный'}`);light.g.querySelector('title').textContent=light.g.getAttribute('aria-label');}
        j.timer.textContent=blockedSeconds>0?`${blockedSeconds} с`:clearance>0?`${clearance} с`:active&&finite(signalState.remaining)>0?`${signalState.remaining} с`:'';
        j.ewPreview.setAttribute('stroke',preview?'#548bae':'#8ac99b');j.nsPreview.setAttribute('stroke',preview?'#9372b5':'#8ac99b');j.ewPreview.setAttribute('opacity',preview&&id===selectedJunction&&(selectedAxis==='EW'||selectedAxis==='BOTH')?.45:(active==='EW'||active==='BOTH')?.25:0);j.nsPreview.setAttribute('opacity',preview&&id===selectedJunction&&(selectedAxis==='NS'||selectedAxis==='BOTH')?.45:(active==='NS'||active==='BOTH')?.25:0);
        const observation=root.TrafficEngine?.observe(state,id);let blocked=false;for(const dir of[1,-1]){const info=observation?.byDirection?.EW?.[dir],jam=info?info.vehicles>0&&info.space===0:dir===1&&observation?.EW.space===0;j.blockDirs[dir].setAttribute('opacity',jam?1:0);blocked=blocked||jam;}j.blocked.setAttribute('opacity',blocked?1:0);j.blocked.setAttribute('aria-hidden',String(!blocked));j.crash.g.setAttribute('opacity',blockedSeconds>0?1:0);j.crash.g.setAttribute('aria-hidden',String(blockedSeconds<=0));j.crash.title.textContent=`СТОЛКНОВЕНИЕ · ${blockedSeconds} с`;
      }
      const queued=queuePositions(state),positions=visibleTraffic(state,queued,aggregatedTrips),visible=new Set(),hiddenQueues={},hiddenMoving={};
      for(const agent of state.agents||[]){const p=positions.get(agent.id);if(p?.hidden){const key=streamKey(p.junction,p.axis,p.dir),groups=p.moving?hiddenMoving:hiddenQueues;(groups[key]||(groups[key]=[])).push(agent);}}
      for(const[id,j]of Object.entries(junctions))for(const[key,tail]of Object.entries(j.tails)){const[axis,dir]=key.split('|'),q=hiddenQueues[streamKey(id,axis,dir)]||[],m=hiddenMoving[streamKey(id,axis,dir)]||[],shown=q.length||m.length;
        tail.g.setAttribute('display',shown?'':'none');tail.g.setAttribute('tabindex',shown?0:-1);tail.g.setAttribute('data-count',q.length);tail.g.setAttribute('data-people',q.reduce((n,a)=>n+a.people,0));tail.g.setAttribute('data-agent-ids',JSON.stringify(q.map(a=>a.id)));tail.moving.setAttribute('display',m.length?'':'none');tail.moving.setAttribute('data-count',m.length);tail.moving.setAttribute('data-people',m.reduce((n,a)=>n+a.people,0));tail.moving.setAttribute('data-agent-ids',JSON.stringify(m.map(a=>a.id)));
        tail.label.setAttribute('display',q.length?'':'none');tail.label.textContent=`Ещё ${q.length}`;tail.movingLabel.textContent=`В пути ${m.length}`;const top=tail.bottom?22:1;tail.bg.setAttribute('height',q.length&&m.length?41:21);tail.bg.setAttribute('y',top);tail.movingLabel.setAttribute('y',(tail.bottom?38:17)+(q.length?20:0));if(shown){tail.g.dataset.agentId=(q[0]||m[0]).id;tail.g.setAttribute('aria-label',`${id}: ${directionName(axis,dir)}, ещё ${q.length} групп ждут, ${m.length} групп в пути. Посмотреть участника.`);}}
      for(const agent of state.agents||[]){if(positions.get(agent.id)?.hidden)continue;const exiting=agent.status==='arrived'&&views.has(agent.id)&&animationEnabled;if(exiting){const view=views.get(agent.id);visible.add(agent.id);if(!view.departing){view.departing=true;view.tween={from:view.current,to:position(agent,queued,state),time:now,duration:interval||200};view.g.setAttribute('data-status','arrived');view.g.classList.add('is-arriving');}continue;}const crashed=agent.status==='crashed',crashEvent=crashed?(state.accidents||[]).find(e=>e.agents.includes(agent.id)&&e.blockedUntil>state.tick):null;if(agent.status!=='queued'&&agent.status!=='moving'&&!crashEvent)continue;visible.add(agent.id);let view=views.get(agent.id);if(!view){view=agentView(agentLayer,agent,onAgent);views.set(agent.id,view);}const collisionNs=crashEvent?(state.agents||[]).find(a=>crashEvent.agents.includes(a.id)&&a.from?.axis==='NS'):null,collisionEw=crashEvent?(state.agents||[]).find(a=>crashEvent.agents.includes(a.id)&&a.from?.axis==='EW'):null,part=agent.status==='queued'?agent.route?.[agent.leg]:agent.from,dir=direction(part),p=crashEvent?{x:layout.junctions[crashEvent.junction]-direction(collisionNs?.from)*25+(agent.from?.axis==='NS'?6:-6),y:(direction(collisionEw?.from)===1?385:335)+(agent.from?.axis==='NS'?-7:7),rotation:agent.from?.axis==='NS'?dir*85:dir===1?12:192,dir}:(positions.get(agent.id)||position(agent,queued,state)),slack=finite(agent.deadline,Infinity)-finite(state.tick),urgent=slack<=12,late=slack<0;
        if(animationEnabled&&view.current){if(interval&&state.tick!==view.tick)view.tween={from:view.current,to:p,time:now,duration:interval};}else {view.tween=null;paint(view,p);}view.tick=state.tick;view.g.setAttribute('class',`traffic-agent traffic-${agent.kind} is-${agent.status}${urgent?' is-urgent':''}${late?' is-late':''}`);view.g.setAttribute('data-status',agent.status);view.g.setAttribute('data-dir',p.dir||direction((agent.status==='queued'?agent.route?.[agent.leg]:agent.from)));view.g.setAttribute('data-progress',String(finite(agent.progress)));view.g.setAttribute('data-people',String(agent.people||1));view.g.setAttribute('aria-label',`${agent.kind==='bus'?'Автобус':agent.kind==='pedestrian'?'Пешеходы':'Машина'}: ${agent.people||1} человек, ${slack<0?'опаздывает на '+(-slack):'до срока '+slack} секунд`);view.g.querySelector('title').textContent=view.g.getAttribute('aria-label');view.ring.setAttribute('opacity',late?.65:urgent?.4:0);view.ring.setAttribute('stroke',late?'#d16f60':'#e9b867');view.badgeBg.setAttribute('fill',late?'#f2c0aa':urgent?'#ffe2a1':'#fff4cd');view.badge.setAttribute('display',agent.kind==='pedestrian'||agent.people>1?'':'none');const side=(agent.status==='queued'?agent.route?.[agent.leg]:agent.from)?.axis;if(agent.kind==='pedestrian'){const vertical=side==='NS',outward=p.dir===1?1:-1;view.badgeBg.setAttribute('x',vertical?(outward===1?11:-37):-14);view.badgeBg.setAttribute('y',vertical?-12:-42);view.badgeBg.setAttribute('width',28);view.number.setAttribute('x',vertical?(outward===1?25:-23):0);view.number.setAttribute('y',vertical?6:-24);}else{view.badgeBg.setAttribute('x',-14);view.badgeBg.setAttribute('y',-12);view.badgeBg.setAttribute('width',28);view.number.setAttribute('x',0);view.number.setAttribute('y',6);}view.number.textContent=String(agent.people||1);view.clock.textContent='';
      }
      for(const [id,view]of views)if(!visible.has(id)){view.g.remove();views.delete(id);}if(animationEnabled&&!animationFrame)animationFrame=root.requestAnimationFrame(frame);
    }
    return {render,destroy(){stopAnimation();animationEnabled=false;svg.replaceChildren();views.clear();aggregatedTrips.clear();},layout};
  }
  root.TrafficMap={init,layout};
})(typeof window!=='undefined'?window:globalThis);
