const fs=require('fs'),vm=require('vm'),assert=require('assert');const base=require('path').join(__dirname,'../');const els={};class El{constructor(tag='div'){this.tag=tag;this.attrs={};this.children=[];this.value='';this.textContent='';this.style={};this.classList={add(){},remove(){}};}set id(v){this._id=v;els[v]=this;}get id(){return this._id;}setAttribute(k,v){this.attrs[k]=v;}appendChild(e){this.children.push(e);}replaceChildren(){this.children=[];}focus(){}scrollIntoView(){}}
const document={getElementById(id){return els[id]??=new El()},createElement:t=>new El(t),createElementNS:(n,t)=>new El(t),addEventListener(){},body:new El()};for(let [id,v]of Object.entries({source:0,seed:1,prob:12,days:5,speed:2400}))document.getElementById(id).value=v;let cb;const ctx={document,Epidemic:require(base+'epidemic.js'),parent:{postMessage(){}},window:{addEventListener(){}},ResizeObserver:class{observe(){}},clearTimeout(){},setTimeout(){},requestAnimationFrame(f){cb=f;},cancelAnimationFrame(){},performance:{now:()=>0},console};vm.createContext(ctx);vm.runInContext([...fs.readFileSync(base+'epidemic.html','utf8').matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].at(-1)[1],ctx);
assert.equal(els.map.children.filter(e=>e.attrs.class==='inhabitant').length,72);els.adult0.value=20;els.adult0.onchange();assert(els.populationTotal.textContent.includes('84'));els.finish.onclick();assert.equal(els.save.disabled,false);els.save.onclick();assert.equal(els.results.children.length,1);els.reset.onclick();vm.runInContext('ensure();frame=1;draw(true);',ctx);cb(500);cb(3000);assert.equal(els.step.disabled,false);
vm.runInContext('state.config.districts=Array.from({length:6},()=>({adults:20,children:20}));for(const k of Object.keys(state.config.rates))state.config.rates[k]=100;invalidate();ensure();frame=1;draw();',ctx);
vm.runInContext(`for(const h of experiment.history){const pos=positions(h);for(const p of Epidemic.places){let n=0;h.loc.forEach((id,i)=>{if(id!==p.id||!pos[i])return;n++;const [x,y]=pos[i];if(x-9<p.x-111||x+9>p.x+111||y-14<p.y+51||y+8>p.y+143)throw Error('Figure escaped courtyard');});if(n>60)throw Error('Crowd bound');}}`,ctx);
console.log('UI settings, finish/save/reset, animation frames and all crowd bounds passed');

vm.runInContext(`for(const p of Epidemic.places){for(const [dx,dy,z] of [[-123,-68,110],[123,184,0]]){const [x,y]=project(p.x+dx,p.y+dy,z);if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||x>1750||y<0||y>1080)throw Error('Isometric scene escaped viewport');}}`,ctx);
assert.equal(els.map.attrs.viewBox,'0 0 1750 1080');els.zoom.onclick();assert.equal(els.map.style.width,'1900px');els.zoom.onclick();assert.equal(els.map.style.width,'100%');console.log('Isometric projection and zoom passed');
