// Controller integration check in a lightweight DOM. Not a browser rendering test.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),M=require('../mayor.js'),E=require('../epidemic.js');const ids={},queue=[];
class El{constructor(tag='div'){this.tag=tag;this.children=[];this.attrs={};this.value='';this.textContent='';this.disabled=false;const classes=new Set();this.classList={add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x),toggle(x){if(classes.has(x)){classes.delete(x);return false;}classes.add(x);return true;}};}set id(v){this.attrs.id=v;ids[v]=this;}get id(){return this.attrs.id;}setAttribute(k,v){this.attrs[k]=v;if(k==='id')this.id=v;}appendChild(e){if(e.parentNode)e.parentNode.children=e.parentNode.children.filter(x=>x!==e);e.parentNode=this;this.children.push(e);return e;}insertBefore(e){this.appendChild(e);}replaceChildren(){this.children=[];}focus(){}scrollIntoView(){}closest(tag){let e=this;while(e&&e.tag!==tag)e=e.parentNode;return e;}querySelectorAll(query){const tags=query.split(',');const result=[];function visit(e){for(const c of e.children){if(tags.includes(c.tag))result.push(c);visit(c);}}visit(this);return result;}set innerHTML(source){const stack=[this];for(const part of source.match(/<[^>]*>|[^<]+/g)||[]){if(part.startsWith('</')){stack.pop();continue;}if(!part.startsWith('<')){stack.at(-1).textContent+=part;continue;}const tag=part.match(/^<([\w-]+)/)?.[1];if(!tag)continue;const e=new El(tag);for(const m of part.matchAll(/([\w-]+)="([^"]*)"/g)){e.setAttribute(m[1],m[2]);if(m[1]==='value')e.value=m[2];}stack.at(-1).appendChild(e);if(!['input','br','hr'].includes(tag))stack.push(e);}}}
const body=new El('body'),main=new El('main'),city=new El('section');body.appendChild(main);main.appendChild(city);let renders=0,lastGame,interval,now=1000;const window={renderMayor(g,h,i){renders++;lastGame=g;assert(i<h.length);},resetMayorMap(){}};
const document={body,createElement:tag=>new El(tag),getElementById:id=>ids[id],querySelector:q=>q==='.city'?city:null};const ctx={document,window,Mayor:M,Contest:require('../contest.js'),Epidemic:E,console,Date:class extends Date{static now(){return now;}},setInterval:f=>interval=f,setTimeout:f=>{queue.push(f);return queue.length;},clearTimeout(){queue.length=0;}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../contest-ui.js'),'utf8'),ctx);
assert.equal(city.parentNode,ids.contestMap);assert(renders>0);ids.roundSeed.value=1;
assert.equal(ids['panel-school'].hidden,false);window.mayorSelect('bus');assert.equal(ids['panel-bus'].hidden,false);assert.equal(ids['panel-school'].hidden,true);assert(!ids.roundSeed.disabled);
for(const [k,v]of Object.entries({school:'shifts',work:'remote',shops:'both',bus:'normal',rest:'park',trigger:'0'})){ids['pick-'+k+'-'+v].onclick();assert.equal(ids['choice-'+k].value,v);}
ids.prediction.value='';ids.tryPlan.onclick();assert(ids.roundSeed.disabled);assert(ids.tryPlan.disabled);while(queue.length)queue.shift()();assert.equal(ids.attemptRows.children.length,1);assert(!ids.tryPlan.disabled);assert(ids.personalBest.textContent.includes('рекорд'));
ids.lockPlan.onclick();while(queue.length)queue.shift()();assert(ids.tryPlan.disabled);assert(ids['choice-school'].disabled);assert(ids.finalCard.children.some(e=>e.textContent.includes('В зачёте')));assert.equal(lastGame.scenario,2);ids.tryPlan.onclick();assert.equal(queue.length,0);
ids.scoreName.value='Команда';ids.scorePeak.value=23;ids.scoreTotal.value=80;ids.scoreValid.checked=true;ids.addScore.onclick();assert.equal(ids.scoreboard.children.length,1);
ids.restartContest.onclick();assert(!ids.roundSeed.disabled);assert(!ids.tryPlan.disabled);assert.equal(ids.attemptRows.children.length,0);assert.equal(ids.prediction.children[1].textContent,'Пик будет ниже 20');
ids.prediction.value='higher';ids.tryPlan.onclick();while(queue.length)queue.shift()();now=422000;interval();while(queue.length)queue.shift()();assert(ids.tryPlan.disabled);assert(ids.finalCard.children.length>0);console.log('Contest UI: prediction, trial, plan lock, second scenario, scoreboard, restart and timer passed');
