const assert=require('node:assert/strict'),E=require('../epidemic.js');
const a=E.simulate({});assert.equal(a.population,72);assert.deepEqual(a,E.simulate({}));
for(const h of a.history){assert.equal(h.S+h.I+h.R,a.population);assert.equal(h.loc.length,a.population);assert.equal(h.outside,h.loc.filter(p=>!p.startsWith('h')).length);for(const e of h.events)assert.equal(h.loc[e.source],h.loc[e.target]);}
assert.equal(a.history.at(-1).I,0);assert.equal(E.simulate({p:0}).total,1);assert.equal(E.simulate({p:0,duration:5}).history.at(-1).day,5);assert.equal(a.peakIndex,a.history.findIndex(h=>h.I===a.peak));assert.deepEqual(a.peakTime,a.history[a.peakIndex]);
const c=E.defaults();Object.keys(c.rates).forEach(k=>c.rates[k]=100);c.rates.clinic=0;c.rates.mall=0;const child={home:'h0',district:0,child:true,key:1},adult={...child,child:false};assert.equal(E.destination(child,1,1,c),'school');assert.equal(E.destination(adult,1,1,c),'work');assert.equal(E.destination(child,2,1,c),'h0');assert.equal(E.destination(adult,2,1,c),'market');assert.equal(E.destination(child,3,1,c),'gym');c.gym=false;assert.equal(E.destination(child,3,1,c),'park');c.school=false;assert.equal(E.destination(child,1,1,c),'h0');c.bus=false;assert.equal(E.destination(adult,0,1,c),'h0');assert.equal(E.destination(adult,1,1,c),'work');
const empty=Array.from({length:6},()=>({adults:0,children:0}));assert.equal(E.simulate({districts:empty}).population,0);empty[4]={adults:0,children:1};const one=E.simulate({districts:empty,initialDistrict:4});assert.equal(one.population,1);assert.equal(one.total,1);assert.equal(one.people[0].home,'h4');
const big=E.simulate({districts:Array.from({length:6},()=>({adults:20,children:20})),p:0});assert.equal(big.population,240);assert.equal(big.total,1);
const none=E.defaults();Object.keys(none.rates).forEach(k=>none.rates[k]=0);assert(E.simulate(none).history.every(h=>h.outside===0));console.log('Population, age routes, attendance, peak timing, zero/max population passed');
// Complete parcel bounds (including title and footer) must stay clear of streets.
for(const p of E.places){assert(p.x-123>=0&&p.x+123<=1000);assert(p.y-91>=0&&p.y+184<=1700);for(const x of [20,340,660,980])assert(p.x+123<=x-18||p.x-123>=x+18);for(const y of [330,660,990,1320,1650])assert(p.y+184<=y-25||p.y-91>=y+25);}
console.log('Parcel bounds clear of roads and canvas edges');

const newRoutes=E.defaults();newRoutes.rates.kindergarten=100;const toddler={home:'h0',child:true,preschool:true,key:50};assert.equal(E.destination(toddler,1,1,newRoutes),'kindergarten');newRoutes.kindergarten=false;assert.equal(E.destination(toddler,1,1,newRoutes),'h0');newRoutes.rates.clinic=100;assert.equal(E.destination(toddler,2,1,newRoutes),'clinic');newRoutes.clinic=false;newRoutes.rates.mall=100;assert.equal(E.destination(toddler,2,1,newRoutes),'mall');newRoutes.mall=false;assert.equal(E.destination(toddler,2,1,newRoutes),'h0');assert.equal(E.places.length,15);assert(E.places.filter(p=>p.home).length===6);for(const h of E.simulate().history)assert(h.loc.every(id=>E.places.some(p=>p.id===id)));console.log('Kindergarten, clinic and mall routes and closures passed');
