// Controller integration check in a lightweight DOM. Not a browser rendering test.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),M=require('../mayor.js'),E=require('../epidemic.js');const ids={},queue=[];
class El{constructor(tag='div'){this.tag=tag;this.children=[];this.attrs={};this.value='';this.textContent='';this.disabled=false;const classes=new Set();this.classList={add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x),toggle(x){if(classes.has(x)){classes.delete(x);return false;}classes.add(x);return true;}};}set id(v){this.attrs.id=v;ids[v]=this;}get id(){return this.attrs.id;}setAttribute(k,v){this.attrs[k]=v;if(k==='id')this.id=v;}appendChild(e){if(e.parentNode)e.parentNode.children=e.parentNode.children.filter(x=>x!==e);e.parentNode=this;this.children.push(e);return e;}insertBefore(e){this.appendChild(e);}replaceChildren(){this.children=[];}focus(){}scrollIntoView(){}closest(tag){let e=this;while(e&&e.tag!==tag)e=e.parentNode;return e;}querySelectorAll(query){const tags=query.split(',');const result=[];function visit(e){for(const c of e.children){if(tags.includes(c.tag))result.push(c);visit(c);}}visit(this);return result;}set innerHTML(source){const stack=[this];for(const part of source.match(/<[^>]*>|[^<]+/g)||[]){if(part.startsWith('</')){stack.pop();continue;}if(!part.startsWith('<')){stack.at(-1).textContent+=part;continue;}const tag=part.match(/^<([\w-]+)/)?.[1];if(!tag)continue;const e=new El(tag);for(const m of part.matchAll(/([\w-]+)="([^"]*)"/g)){e.setAttribute(m[1],m[2]);if(m[1]==='value')e.value=m[2];}stack.at(-1).appendChild(e);if(!['input','br','hr'].includes(tag))stack.push(e);}}}
const body=new El('body'),main=new El('main'),city=new El('section');body.appendChild(main);main.appendChild(city);let renders=0,lastGame;
const window={renderMayor(g,h,i){renders++;lastGame=g;assert(i<h.length);assert(h[i].loc.length===g.people.length);}};
ids.map=new El('svg');
const document={body,createElement:tag=>new El(tag),createElementNS:(ns,tag)=>new El(tag),getElementById:id=>ids[id],querySelector:q=>q==='.city'?city:null};
const ctx={document,window,parent:window,location:{search:''},URLSearchParams,GameScore:require('../game-score.js'),Mayor:M,Epidemic:E,console,setTimeout:f=>{queue.push(f);return queue.length;},clearTimeout(){queue.length=0;}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../mayor-ui.js'),'utf8'),ctx);
assert(window.mayorActive);assert.equal(city.parentNode,ids.mayorMapSlot);assert(renders>0);assert(ids.tryCity.disabled);
ids.observeCity.onclick();while(queue.length)queue.shift()();assert(!ids.tryCity.disabled);assert(ids.cityStart.hidden);assert.equal(lastGame.day,14);assert.equal(ids.cityLocalScore.textContent,'0 / 50','The demonstration earns no points');
ids['pick-bus-frequent'].onclick();ids.tryCity.onclick();assert(ids.tryCity.disabled);while(queue.length)queue.shift()();assert.equal(ids.cityAttempts.children.length,1);const first=ids.cityLocalScore.textContent;
ids['pick-school-shifts'].onclick();ids.tryCity.onclick();while(queue.length)queue.shift()();assert.equal(ids.cityAttempts.children.length,2);assert(parseInt(ids.cityLocalScore.textContent)>parseInt(first));const best=ids.cityLocalScore.textContent;
ids['pick-shops-one'].onclick();ids.tryCity.onclick();while(queue.length)queue.shift()();assert.equal(ids.cityAttempts.children.length,3);assert.equal(ids.cityLocalScore.textContent,best,'A weaker attempt does not erase the best');assert(ids.tryCity.disabled);assert(ids['pick-bus-normal'].disabled);
ids.tryCity.onclick();assert.equal(queue.length,0);window.mayorCitizenSelect(0);assert(ids.cityPeople.open);assert.equal(ids.citizenPanel.children[0].children.find(e=>e.tag==='ol').children.length,5);assert(window.cityTourHooks.before());
console.log('City UI: free baseline, choices, three full attempts, best score and citizen routes passed');
