const assert = require('node:assert/strict');
const S = require('../game-score.js');
const original = S.cityRun(S.cityDefaults());
const good = S.cityRun({school:'shifts',bus:'frequent',shops:'both'});
const noFood = S.cityRun({school:'shifts',bus:'frequent',shops:'one'});
const noTrips = S.cityRun({school:'shifts',bus:'reduced',shops:'both'});
assert.equal(original.game.day,14);
assert.equal(original.game.people.length,90);
assert(good.total < original.total, 'Separated shifts should reduce infections');
assert(good.missed < original.missed, 'More buses should improve access');
assert(good.activity > original.activity);
assert(good.score > original.score);
assert(noFood.food < 80 && noFood.score <= 25, 'Avoiding infections cannot compensate for missing food');
assert(noTrips.activity < 70 && noTrips.score <= 25, 'Avoiding infections cannot compensate for inaccessible school/work');
assert.deepEqual(S.cityRun(good.plan),good, 'Every attempt starts with identical initial conditions');
assert.throws(()=>S.cityRun({school:'invented',bus:'normal',shops:'both'}));
assert.equal(S.total({robot:50,city:50}),100);
assert.equal(S.total({robot:999,city:-1}),50);
assert.equal(S.total(),0);
console.log('Scores: unchanged city tradeoffs, repeatability and robot/city score limits passed');
